### ISSUE TITLE
Mobile Setting for ImageNet

### ISSUE THREAD

**Issue by chenwydj** [xiangning-chen/DrNAS#1]
Thanks for the great work!

1. Is `train_search_imagenet.py` under the mobile setting?
2. Could you explain the details about the mobile setting?
    1. I only found "input image size is 224×224" and "the number of multiply-add operations in the model is restricted to be less than 600M". Are these all?
    2. Is this setting applied during search or train-from-scratch, and how to apply them? I could not see any FLOPs constraint during search or train-from-scratch.

Thank you!

**Comment by xiangning-chen** [comment]
Hi,

Thanks for your question.
The focus of our work is on searching model with high accuracy. So we didn't apply any FLOPs constraint during search.
However, the DARTS space is designed for mobile settings (without normal convolution), and the generated architecture by DrNAS meets the mobile constraint.
We are thinking of adding FLOPs constraint in the future. Because under extreme circumstances (e.g. the operation on every edge is convolution), the number of multiply-add operations can exceed 600M.
